name: bubbles_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  firebase_auth: ^4.2.5
  firebase_analytics: ^10.1.0
  cloud_firestore: ^4.3.1
  provider: ^6.0.5
  get_it: "7.2.0"
  file_picker: ^5.2.5
  flutter_spinkit: "5.1.0"
  timeago: ^3.3.0
  flutter_keyboard_visibility: ^5.4.0
  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  flutter_map: ^4.0.0
  network_info_plus: ^3.0.2
  flutter_geo_hash: ^0.0.4
  url_launcher: ^6.1.10
  flashy_tab_bar2: ^0.0.6
  async_button_builder: ^3.0.0+1
  easy_autocomplete: ^1.6.0
  list_picker: ^1.1.0
  translator: ^0.1.7
  comment_tree: ^0.3.0
  geocoding: ^2.1.0
  nfc_manager: ^3.2.0
  permission_handler: ^10.2.0







dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
